---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy
spec:
  template:
    spec:
      containers:
      - name: envoy
        volumeMounts:
        - $patch: replace
        - name: envoy-config
          mountPath: /config
      initContainers:
      - name: envoy-initconfig
        args:
        - bootstrap
        - /config/envoy.json
        - --xds-address=$(CONTOUR_XDS_ADDRESS)
        - --xds-port=$(CONTOUR_XDS_PORT)
        volumeMounts:
        - $patch: replace
        - name: envoy-config
          mountPath: /config
      volumes:
      - $patch: replace
      - emptyDir: {}
        name: envoy-config

