apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour

bases:
- ../../types
- ../../base

resources:
- namespaces.yaml

patches:

# Make the Envoy a NodePort service.
- enable-nodeport.yaml

# Enable Envoy debug logging.
- enable-envoy-debug.yaml

# Disable TLS for the xDS session between Contour and Envoy. Remove
# the boostrap init container and provide the Envoy bootstrap through a
# ConfigMap volume. Remove Contour xDS certificate and CA secrets volumes.
- update-envoy-daemonset.yaml

# Scale the Contour deployment to 0, because the developer will manually
# run a development Contour build.
- scale-contour-down.yaml

configMapGenerator:
- name: envoy-bootstrap
  files:
  - configs/envoy.json
