
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /status/200
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: &name httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: *name
