apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour

bases:
- ../../types
- ../../base
- ../../certgen

resources:
- namespaces.yaml

patches:
- enable-nodeport.yaml
