apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fedora
  name: fedora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fedora
    spec:
      containers:
      - name: fedora
        image: docker.io/fedora:32
        command:
        - /bin/sleep
        args:
        - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
