apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour-internal
nameSuffix: -internal

bases:
- ../../../../contour/types
- ../../../../contour/base

resources:
- namespaces.yaml
