apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour-internal
nameSuffix: -internal

bases:
- ../../../../contour/base
- ../../../../contour/certgen

resources:
- namespaces.yaml

patchesStrategicMerge:
- envoy-node-selector.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: contour-internal
    namespace: projectcontour-internal
  path: ingress-class.yaml

configMapGenerator:
- name: contour
  behavior: replace
  files:
  - configs/contour.yaml
