apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour-external
nameSuffix: -external

bases:
- ../../../../contour/base

resources:
- namespaces.yaml

patchesStrategicMerge:
- envoy-node-selector.yaml

configMapGenerator:
- name: contour
  behavior: replace
  files:
  - configs/contour.yaml
