apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name ingress-conformance-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      containers:
      - name: conformance-echo
        image: agervais/ingress-conformance-echo:latest
        env:
        - name: TEST_ID
          value: *name
        ports:
        - name: http-api
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: &name ingress-conformance-echo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http-api
  selector:
    app.kubernetes.io/name: *name

