apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbin-2
spec:
  virtualhost:
    fqdn: httpbin-2.jpeach.org
    tls:
      secretName: httpbin-2
  routes:
    - conditions:
      - prefix: /
      services:
        - name: httpbin
          port: 80

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: httpbin-2-cert
spec:
  dnsNames:
    - httpbin-2.jpeach.org
  secretName: httpbin-2
  issuerRef:
    name: test-selfsigned
