apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../contour/types
- ../../base

resources:
- net-contour-clusterrole.yaml
- net-contour-controller.yaml
- net-contour-config.yaml

configMapGenerator:
- name: config-contour
  namespace: knative-serving
  behavior: replace
  files:
  - configs/visibility
- name: config-network
  namespace: knative-serving
  behavior: merge
  literals:
  - ingress.class=contour.ingress.networking.knative.dev

images:
- name: github.com/mattmoor/net-contour/cmd/controller
  newName: docker.io/jpeach/net-contour
  newTag: "3"
