apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour

bases:
- ../../types
- ../../base
- ../../certgen

resources:
- namespaces.yaml

patchesStrategicMerge:
- enable-tcp-balancer.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: contour
    namespace: projectcontour
  path: enable-proxy-protocol.yaml
