# should contour expect to be running inside a k8s cluster
# incluster: true

# path to kubeconfig (if not running inside a k8s cluster)
# kubeconfig: /path/to/.kube/config

# Client request timeout to be passed to Envoy
# as the connection manager request_timeout.
# Defaults to 0, which Envoy interprets as disabled.
# Note that this is the timeout for the whole request,
# not an idle timeout.
# request-timeout: 0s

# Disable ingressroute permitInsecure field.
disablePermitInsecure: false

tls:
#   minimum TLS version that Contour will negotiate
#   minimum-protocol-version: "1.1"

# The following config shows the defaults for the leader election.
leaderelection:
  configmap-name: leader-elect
  configmap-namespace: projectcontour-internal

# Logging options
accesslog-format: envoy
