---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbin
spec:
  virtualhost:
    fqdn: httpbin.jpeach.org
  routes:
    - conditions:
      - prefix: /
      services:
        - name: httpbin
          port: 80
